platform :osx, '10.10'
use_frameworks!

target 'Grid_DEV' do
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'DJProgressHUD_OSX','0.0.1'
    pod 'AFNetworking', '~> 3.0'
    pod 'BFColorPickerPopover'
    pod 'SYFlatButton'
    pod 'RFOverlayScrollView'
    pod 'CocoaAsyncSocket'
    pod 'ObjectiveDropboxOfficial'
    pod 'OGSwitch', :git => 'https://github.com/OskarGroth/OGSwitch.git', :commit => '5de34130036bd09aedb78a5af00082a9b1cfeac5'
end

target 'Grid' do
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'DJProgressHUD_OSX','0.0.1'
  pod 'AFNetworking', '~> 3.0'
  pod 'BFColorPickerPopover'
  pod 'SYFlatButton'
  pod 'RFOverlayScrollView'
  pod 'CocoaAsyncSocket'
  pod 'ObjectiveDropboxOfficial'
  pod 'OGSwitch', :git => 'https://github.com/OskarGroth/OGSwitch.git', :commit => '5de34130036bd09aedb78a5af00082a9b1cfeac5'
end

target 'Grid_UAT' do
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'DJProgressHUD_OSX','0.0.1'
    pod 'AFNetworking', '~> 3.0'
    pod 'BFColorPickerPopover'
    pod 'SYFlatButton'
    pod 'RFOverlayScrollView'
    pod 'CocoaAsyncSocket'
    pod 'ObjectiveDropboxOfficial'
    pod 'OGSwitch', :git => 'https://github.com/OskarGroth/OGSwitch.git', :commit => '5de34130036bd09aedb78a5af00082a9b1cfeac5'
end
